better find project

diff --git a/project_management/dev b/project_management/dev
--- a/project_management/dev
+++ b/project_management/dev
@@ -1,16 +1,41 @@
 #!/usr/bin/env bash
-
-# helpers
 starts_with() {
   [[ $1 == $2 ]] || [[ $1 == $2* ]] || return 1
 }
 
-normalize_path() {
-  local normalized="$1"
-  if starts_with "$normalized" "."; then
-    normalized="$PWD/$normalized"
+cur_env=$(cat $ENV_FILE)
+DEV_DIR=$(realpath "$DEV_DIR")
+ENV_DIR=$(realpath "$DEV_DIR/$cur_env")
+
+check_dir() {
+  local dir="$1"
+  local proj="$2"
+  cd $dir || return 1
+  local real=$(realpath "$dir/$proj") || return 1
+  [[ -d "$real" ]] || return 1
+  starts_with $real $dir || return 1
+  echo $real
+  return 0
+}
+
+find_project() {
+  local x
+  # look for relative path first if begins with . or /
+  if echo $1 | grep -qE '^(\.|\/)'; then
+    if ! x=$(realpath $1); then
+      echo "Can't find $x"
+      exit 1
+    fi
+  else
+    # otherwise check other directories
+    x=$(check_dir "$ENV_DIR" "$1") || x=$(check_dir "$DEV_DIR" "$1") || x=$(realpath $1)
   fi
-  echo "$normalized" | tr -s / | sed 's/\/\.\//\//g' | sed 's/\/\.$//'
+
+  if starts_with "$x" "$DEV_DIR"; then
+    echo ${x:$((${#DEV_DIR} + 1))}
+  else
+    echo $x
+  fi
 }
 
 if [ -z "$1" ]; then
@@ -19,48 +44,42 @@ if [ -z "$1" ]; then
   return $?
 fi
 
-# make absolute if relative
-start_path=$1
-normalized="$(normalize_path $start_path)"
+project="$(find_project $1)"
+if starts_with "$project" "/"; then
+  project_full="$project"
+else
+  project_full="$DEV_DIR/$project"
+fi
 
-cur_env=$(cat $ENV_FILE)
-paths=("${DEV_DIR}/${cur_env}" "${DEV_DIR}" "." "/")
-project=""
-for p in "${paths[@]}" ; do
-  if [ -d "${p}/${normalized}/.git" ]; then
-    project=$(normalize_path "$p/$normalized")
-    break
-  fi
-done
-
-if [ -z "$project" ]; then
-  echo -n "Couldn't find project $1."
-  if [ "$(normalize_path $1)" != "$PWD" ]; then
-    create_dir=$cur_env/$1
+if [ ! -d "$project_full" ]; then
+  if starts_with "$1" "/" || starts_with "$1" "."; then
+    create_dir="$(realpath $1)"
+  elif [ $1  != */* ]; then
+    create_dir=$ENV_DIR/$1
+  elif [ -d $DEV_DIR/${1%%/*} ]; then
+    create_dir=$DEV_DIR/$1
   else
-    create_dir=$start_path
+    create_dir=$ENV_DIR/$1
   fi
-  if getyn "Init project in $create_dir (Y/n)? "; then
-    init_project $create_dir
+  if starts_with "$create_dir" "$DEV_DIR"; then
+    short_dir=${create_dir:$((${#DEV_DIR} + 1))}
+  else
+    short_dir=$create_dir
+  fi
+  if getyn "Couldn't find project $1. Init project in $short_dir (Y/n)? "; then
+    init_project $create_dir || exit 1
     dev $create_dir
-    exit $?
   fi
   exit 1
 fi
 
 # if not in dev dir, use absolute path
-if starts_with "$project" "$DEV_DIR/"; then
-  relpath=${project:$((${#DEV_DIR}+1))}
+if ! starts_with "$project" "/"; then
   # give each project its own history
-  hist_file=$HOME/.histories/.zsh_history_$(echo $relpath | sed 's/\//_/g')
-  # for tracking most recently used projects
-  echo $relpath >> $DEV_HIST
-else 
-  relpath=$project
-  hist_file=$HOME/.zsh_history
+  hist_file=$HOME/.histories/.zsh_history_$(echo $project | sed 's/\//_/g')
 fi
 
-window_name="$(echo "$relpath" | sed 's/\./_dot_/g')"
+window_name="$(echo "$project" | sed 's/\./_/g')"
 contains() {
   while read line; do 
     if [ "$line" == "$1" ]; then
@@ -73,7 +92,7 @@ contains() {
 mkdir -p ${hist_file%/*}
 if [ -z $TMUX ]; then
   session_name=$(tty)
-  tmux new-session -d -c "$project" \
+  tmux new-session -d -c "$project_full" \
     -e "hist_file=$hist_file" \
     -e status_shown=false \
     -s "$session_name" \
@@ -86,19 +105,16 @@ else
   windows=$(tmux list-windows -t $cur_sess -F '#{window_name}')
   if [ "$cur_win" == "$window_name" ]; then
     if [ -z $VIMRUNTIME ]; then
-      cd "$project"
-      $EDITOR $project
+      $EDITOR "$project_full"
+    elif [ "$project" == "$PWD" ]; then
+      echo already on $window_name
     else
-      if [ "$project" != "$PWD" ]; then
-        cd $project
-      else
-        echo already on $window_name
-      fi
+      echo already on $window_name # can't cd, todo
     fi
   elif echo "$windows" |  contains "$window_name"; then
     tmux select-window -t $window_name
   else
-    tmux new-window -d -c "$project" \
+    tmux new-window -d -c "$project_full" \
       -e "hist_file=$hist_file" \
       -e status_shown=false \
       -t "$cur_sess" \
